training-peaks:
  api-url: https://tpapi.trainingpeaks.com
  auth-cookie:

intervals:
  api-url: https://intervals.icu
  password:
  athlete-id:

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:file:./database
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
