training-peaks:
  api-url: https://tpapi.trainingpeaks.com

intervals:
  api-url: https://intervals.icu

trainer-road:
  api-url: https://www.trainerroad.com

app:
  db-path: ./tp2intervals.db

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:sqlite:${app.db-path}
    driver-class-name: org.sqlite.JDBC
  jpa:
    open-in-view: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect

logging:
  file:
    name: tp2intervals.log
