training-peaks:
  api-url: https://tpapi.trainingpeaks.com
  auth-cookie:

intervals:
  api-url: https://intervals.icu
  login: API_KEY
  password:
  athlete-id:

spring:
  jackson:
    default-property-inclusion: non_null
