training-peaks:
  api-url: https://tpapi.trainingpeaks.com

intervals:
  api-url: https://intervals.icu

trainer-road:
  api-url: https://www.trainerroad.com

app:
  plan-workouts-cron: 0 22 * * *

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:sqlite:tp2intervals-db/db
    driver-class-name: org.sqlite.JDBC
  jpa:
    open-in-view: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect

org:
  jobrunr:
    dashboard:
      enabled: true
    background-job-server:
      enabled: true
