training-peaks:
  api-url: https://tpapi.trainingpeaks.com

intervals:
  api-url: https://intervals.icu

trainer-road:
  api-url: https://www.trainerroad.com

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:file:./tp2intervals-db
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
