openapi: 3.0.3

info:
  title: Api Documentation
  version: 0.0.1

paths:
  /api/test-connections:
    get:
      summary: Test connections to external services
      operationId: testConnections
      responses:
        200:
          description: OK
