name: build

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'corretto'

      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Build backend
        working-directory: ./boot
        run: ./gradlew build

      - name: Build frontend
        working-directory: ./ui
        run: npm ci && npm run build
