name: Build Docker Image

on:
  workflow_call:
    inputs:
      jar-name:
        required: true
        type: string
      jar-artifact-name:
        required: true
        type: string
      image-name:
        required: true
        type: string

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/download-artifact@master
        with:
          name: ${{ inputs.jar-artifact-name }}
          path: artifact

      - name: Build project
        run: docker build . --file Dockerfile --tag ${{ inputs.image-name }} --build-arg JAR_PATH=artifact/${{ inputs.jar-name }}-*.jar

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ inputs.image-name }}:latest
          outputs: type=docker,dest=docker-image/${{ inputs.image-name }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.image-name }}-docker
          path: docker-image/${{ inputs.image-name }}.tar
