name: Build JAR

on:
  workflow_call:
    inputs:
      jar-name:
        required: true
        type: string

jobs:
  build-jar:
    runs-on: ubuntu-latest
    env:
      artifact-name: ${{ inputs.jar-name }}-jar
    outputs:
      artifact-name: ${{ steps.output-step.outputs.artifact-name }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'gradle'

      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: 'npm'
          cache-dependency-path: 'ui/package-lock.json'

      - name: Build project
        run: ./scripts/build-jar.sh

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact-name }}
          path: boot/build/libs/${{ inputs.jar-name }}-[0-9].[0-9].[0-9].jar
          if-no-files-found: error
          compression-level: 0

      - id: output-step
        name: Output artifact name
        run: echo "artifact-name=${{ env.artifact-name }}" >> "$GITHUB_OUTPUT"
