name: build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: tp2intervals
  JAR_NAME: tp2intervals

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'gradle'

      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Build backend
        working-directory: ./boot
        run: ./gradlew build

      - name: Build frontend
        working-directory: ./ui
        run: npm ci && npm run build

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --build-arg JAR_NAME=$JAR_NAME-*.jar
