name: Build JAR

on:
  workflow_call:
    inputs:
      jar-name:
        required: true
        type: string
      jar-artifact-name:
        required: true
        type: string

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'gradle'

      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: 'npm'
          cache-dependency-path: 'ui/package-lock.json'

      - name: Build project
        run: ./scripts/build-jar.sh

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.jar-artifact-name }}
          path: boot/build/libs/${{ inputs.jar-name }}-[0-9].[0-9].[0-9].jar
          if-no-files-found: error
          compression-level: 0
