name: Dev release

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  jar:
    uses: ./.github/workflows/workflow-jar.yml
    secrets: inherit
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar

  docker-image:
    needs:
      - jar
    uses: ./.github/workflows/workflow-docker-image.yml
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar
      image-name: tp2intervals

  electron:
    needs:
      - jar
    strategy:
      matrix:
        environment:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    uses: ./.github/workflows/workflow-electron.yml
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar
      os: ${{ matrix.environment.os }}

  dev-release:
    needs:
      - jar
      - electron
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Show me what you got
        run: ls artifacts