name: Release

on:
  push:
    tags: [v*]
  workflow_dispatch:

jobs:
  jar:
    uses: ./.github/workflows/build-jar.yml
    secrets: inherit
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar
      dry-run: false

  docker-image:
    needs:
      - jar
    uses: ./.github/workflows/build-docker-image.yml
    secrets: inherit
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar
      image-name: tp2intervals
      dry-run: false

  electron:
    uses: ./.github/workflows/build-electron.yml
    secrets: inherit
    with:
      dry-run: false
